# Generated by Django 2.2.1 on 2019-06-18 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_user_customer_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
