# Generated by Django 2.2.1 on 2019-06-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_addresses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address',
            new_name='line1',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='zip',
            new_name='postal_code',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='line2',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
