# Generated by Django 2.2.1 on 2019-06-14 14:41

import carts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_cart_cart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[(carts.models.StatusChoice('CREATED'), 'CREATED'), (carts.models.StatusChoice('CLOSED'), 'CLOSED')], default=carts.models.StatusChoice('CREATED'), max_length=50),
        ),
    ]
