# Generated by Django 2.2.1 on 2019-06-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_cartproducts'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='cart',
            name='products'
        ),

        #migrations.AlterField(
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, through='carts.CartProducts', to='products.Product'),
        ),
    ]
