# Generated by Django 2.2.1 on 2019-06-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
