# Generated by Django 2.2.1 on 2019-06-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_profiles', '0002_billingprofile_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='brand',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='card_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='last4',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
