# Generated by Django 2.2.1 on 2019-06-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_profiles', '0003_auto_20190618_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
