# Generated by Django 2.2.1 on 2019-06-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_profiles', '0004_billingprofile_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='billingprofile',
            name='card_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
