# Generated by Django 2.2.1 on 2019-06-15 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo_codes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
