# Generated by Django 2.2.1 on 2019-06-24 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import orders.common


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing_profiles', '0004_billingprofile_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promo_codes', '0002_auto_20190615_0349'),
        ('shipping_addresses', '0001_initial'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[(orders.common.OrderStatus('CREATED'), 'CREATED'), (orders.common.OrderStatus('PAYED'), 'PAYED'), (orders.common.OrderStatus('COMPLETED'), 'COMPLETED'), (orders.common.OrderStatus('CANCELED'), 'CANCELED')], default=orders.common.OrderStatus('CREATED'), max_length=50)),
                ('shipping_total', models.DecimalField(decimal_places=2, default=4.69, max_digits=100)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('billing_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing_profiles.BillingProfile')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.Cart')),
                ('promo_code', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='promo_codes.PromoCode')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shipping_addresses.ShippingAddress')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
