# Generated by Django 2.2.1 on 2019-06-13 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190613_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='billing_profile',
            new_name='shipping_address',
        ),
    ]
